# frozen_string_literal: true

source 'https://rubygems.org'

ruby '2.6.3'

# Use Puma as the app server

gem 'puma', '~> 3.11'
gem 'redis-sinatra'
gem 'sinatra'
gem 'sinatra-contrib'
# gem 'opentelemetry-instrumentation-all'
gem 'opentelemetry-instrumentation-rack'
gem 'opentelemetry-instrumentation-sinatra'
gem 'opentelemetry-instrumentation-faraday'
gem 'opentelemetry-instrumentation-redis'
gem 'opentelemetry-instrumentation-http'
gem 'opentelemetry-sdk'
gem 'opentelemetry-api'
gem 'opentelemetry-exporter-otlp'
gem 'opentelemetry-exporter-jaeger'
gem "octokit", "~> 4.0"
gem "github_api"

gem 'ddtrace'

